## Ler todos as Matriculas
GET http://localhost:8080/api/v1/matriculas

### Inserir uma nova Matricula
POST http://localhost:8080/api/v1/matriculas
Content-Type: application/json

{
  "dataIngresso": "2022-11-09",
  "periodoCursando": "1",
  "cpfAluno": "111.222.333-44"
}

### Atualizar o  Carro
PUT http://localhost:8080/api/v1/matriculas/eb936e3d-e3e0-4a79-a68f-9b6e51f5ab2b
Content-Type: application/json

{
  "dataIngresso": "2023-01-01",
  "periodoCursando": "1"
}

### Remover o Carro
DELETE  http://localhost:8080/api/v1/matriculas/152c1399-84fe-42b0-b2c6-6cc736372e27
Content-Type: application/json
