## Ler todos as Matriculas
GET http://localhost:8080/api/v1/matriculas

### Inserir uma nova Matricula
POST http://localhost:8080/api/v1/matriculas
Content-Type: application/json

{
  "CPF": "4298-1238-123-12",
  "dataIngresso": "2023-11-09",
  "periodoCursando": "6"
}

### Atualizar o  Carro
PUT http://localhost:8080/api/v1/matriculas/eb936e3d-e3e0-4a79-a68f-9b6e51f5ab2b
Content-Type: application/json

{
  "CPF": "ZZZZZZZZZZ",
  "dataIngresso": "2021-01-01",
  "periodoCursando": "1"
}

### Remover o Carro
DELETE  http://localhost:8080/api/v1/matriculas/0000001
Content-Type: application/json