## Ler todos as Matriculas
GET http://localhost:8080/api/v1/matriculas

### Inserir uma nova Matricula
POST http://localhost:8080/api/v1/matriculas
Content-Type: application/json

{
  "dataIngresso": "2023-11-09",
  "periodoCursando": "3",
  "cpf": "123.434.755-10",
  "alunoId": "c65a51bb-6bd1-420c-a0db-d82c22d7215ft",
  "cursoId": "6c02ccb6-7855-4b24-9056-e28af1e63d84"
}

### Atualizar o  Carro
PUT http://localhost:8080/api/v1/matriculas/c65a51bb-6bd1-420c-a0db-d82c22d7215f
Content-Type: application/json

{
  "dataIngresso": "2023-01-01",
  "periodoCursando": "1",
  "cpf": "222.333.444-55"
}

### Remover o Carro
DELETE  http://localhost:8080/api/v1/matriculas/c65a51bb-6bd1-420c-a0db-d82c22d7215f
Content-Type: application/json
